[sdl]
fullscreen=false
output=surface

[dosbox]
machine=svga_s3
memsize=32

[render]
frameskip=0
aspect=false
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=max

[autoexec]
mount C ..
C:
cd downloads
test-compile.bat

