/**
 * DosKit - Cross-Platform DOS Emulator
 * Copyright (c) 2025 Cameron Rye
 * Licensed under the MIT License
 *
 * Batch File Generator
 * Generates DOS batch files for Open Watcom compilation
 */

/**
 * Batch file generation options
 */
export interface BatchFileOptions {
  /** Working directory for batch file */
  workingDir?: string;
  
  /** Whether to echo commands (default: false) */
  echoCommands?: boolean;
  
  /** Additional environment variables */
  envVars?: Record<string, string>;
}

/**
 * Compile batch file parameters
 */
export interface CompileBatchParams {
  /** Source file path (e.g., "C:\\TEMP\\SOURCE.C") */
  sourcePath: string;
  
  /** Object file path (e.g., "C:\\TEMP\\SOURCE.OBJ") */
  objPath: string;
  
  /** Compiler flags (e.g., "-ms -w4 -ox") */
  compilerFlags: string;
  
  /** Path to wcc.exe */
  compilerBin: string;
  
  /** Include path */
  includePath: string;
  
  /** WATCOM installation path */
  watcomPath: string;
}

/**
 * Link batch file parameters
 */
export interface LinkBatchParams {
  /** Object file paths */
  objPaths: string[];
  
  /** Executable path (e.g., "C:\\OUTPUT\\PROGRAM.EXE") */
  exePath: string;
  
  /** Linker flags (e.g., "SYSTEM DOS") */
  linkerFlags: string;
  
  /** Path to wlink.exe */
  linkerBin: string;
  
  /** Library path */
  libPath: string;
  
  /** WATCOM installation path */
  watcomPath: string;
}

/**
 * Batch File Generator
 * 
 * Generates DOS batch files for Open Watcom compilation and linking.
 * Includes environment setup, error handling, and success/failure markers.
 * 
 * @example
 * ```typescript
 * const batchContent = BatchFileGenerator.generateCompileBatch({
 *   sourcePath: 'C:\\TEMP\\HELLO.C',
 *   objPath: 'C:\\TEMP\\HELLO.OBJ',
 *   compilerFlags: '-ms -w4',
 *   compilerBin: 'C:\\WATCOM\\BINW\\WCC.EXE',
 *   includePath: 'C:\\WATCOM\\H',
 *   watcomPath: 'C:\\WATCOM'
 * });
 * ```
 */
export class BatchFileGenerator {
  /**
   * Generate batch file for compilation
   * 
   * Creates a DOS batch file that:
   * 1. Sets up Open Watcom environment variables
   * 2. Compiles the source file to an object file
   * 3. Checks for errors and outputs success/failure markers
   * 
   * @param params - Compilation parameters
   * @param options - Batch file options
   * @returns Batch file content as string
   * 
   * @example
   * ```typescript
   * const batch = BatchFileGenerator.generateCompileBatch({
   *   sourcePath: 'C:\\TEMP\\MAIN.C',
   *   objPath: 'C:\\TEMP\\MAIN.OBJ',
   *   compilerFlags: '-ms -ox',
   *   compilerBin: 'C:\\WATCOM\\BINW\\WCC.EXE',
   *   includePath: 'C:\\WATCOM\\H',
   *   watcomPath: 'C:\\WATCOM'
   * });
   * ```
   */
  static generateCompileBatch(
    params: CompileBatchParams,
    options?: BatchFileOptions
  ): string {
    const lines: string[] = [];
    
    // Echo control
    if (!options?.echoCommands) {
      lines.push('@echo off');
    }
    
    // Header
    lines.push('REM Open Watcom Compilation Batch File');
    lines.push('REM Generated by DosKit');
    lines.push('');
    
    // Environment setup
    lines.push(...this.generateEnvSetupLines(params.watcomPath, options));
    lines.push('');
    
    // Change to working directory if specified
    if (options?.workingDir) {
      lines.push(`CD ${options.workingDir}`);
      lines.push('');
    }
    
    // Compilation
    lines.push('REM Compile source file');
    lines.push('ECHO Compiling source file...');
    lines.push(`${params.compilerBin} ${params.sourcePath} -FO=${params.objPath} ${params.compilerFlags}`);
    lines.push('');
    
    // Error checking
    lines.push('REM Check for errors');
    lines.push('IF ERRORLEVEL 1 GOTO ERROR');
    lines.push('');
    
    // Success marker
    lines.push('REM Success marker');
    lines.push('ECHO <<<COMPILE_SUCCESS>>>');
    lines.push('GOTO END');
    lines.push('');
    
    // Error label
    lines.push(':ERROR');
    lines.push('ECHO <<<COMPILE_ERROR>>>');
    lines.push('GOTO END');
    lines.push('');
    
    // End label
    lines.push(':END');
    
    return lines.join('\r\n');
  }

  /**
   * Generate batch file for linking
   * 
   * Creates a DOS batch file that:
   * 1. Sets up Open Watcom environment variables
   * 2. Links object files to create an executable
   * 3. Checks for errors and outputs success/failure markers
   * 
   * @param params - Linking parameters
   * @param options - Batch file options
   * @returns Batch file content as string
   * 
   * @example
   * ```typescript
   * const batch = BatchFileGenerator.generateLinkBatch({
   *   objPaths: ['C:\\TEMP\\MAIN.OBJ', 'C:\\TEMP\\HELPER.OBJ'],
   *   exePath: 'C:\\OUTPUT\\PROGRAM.EXE',
   *   linkerFlags: 'SYSTEM DOS',
   *   linkerBin: 'C:\\WATCOM\\BINW\\WLINK.EXE',
   *   libPath: 'C:\\WATCOM\\LIB286\\DOS',
   *   watcomPath: 'C:\\WATCOM'
   * });
   * ```
   */
  static generateLinkBatch(
    params: LinkBatchParams,
    options?: BatchFileOptions
  ): string {
    const lines: string[] = [];
    
    // Echo control
    if (!options?.echoCommands) {
      lines.push('@echo off');
    }
    
    // Header
    lines.push('REM Open Watcom Linking Batch File');
    lines.push('REM Generated by DosKit');
    lines.push('');
    
    // Environment setup
    lines.push(...this.generateEnvSetupLines(params.watcomPath, options));
    lines.push('');
    
    // Change to working directory if specified
    if (options?.workingDir) {
      lines.push(`CD ${options.workingDir}`);
      lines.push('');
    }
    
    // Linking
    lines.push('REM Link object files');
    lines.push('ECHO Linking object files...');
    
    // Build linker command with multiple object files
    const objList = params.objPaths.map(path => `FILE ${path}`).join(' ');
    lines.push(`${params.linkerBin} ${objList} NAME ${params.exePath} ${params.linkerFlags}`);
    lines.push('');
    
    // Error checking
    lines.push('REM Check for errors');
    lines.push('IF ERRORLEVEL 1 GOTO ERROR');
    lines.push('');
    
    // Success marker
    lines.push('REM Success marker');
    lines.push('ECHO <<<LINK_SUCCESS>>>');
    lines.push('GOTO END');
    lines.push('');
    
    // Error label
    lines.push(':ERROR');
    lines.push('ECHO <<<LINK_ERROR>>>');
    lines.push('GOTO END');
    lines.push('');
    
    // End label
    lines.push(':END');
    
    return lines.join('\r\n');
  }

  /**
   * Generate environment setup lines
   * 
   * Creates batch file lines that set up the Open Watcom environment:
   * - WATCOM path
   * - PATH with compiler binaries
   * - INCLUDE path for headers
   * - LIB path for libraries
   * 
   * @param watcomPath - Path to WATCOM installation
   * @param options - Batch file options
   * @returns Array of batch file lines
   */
  private static generateEnvSetupLines(
    watcomPath: string,
    options?: BatchFileOptions
  ): string[] {
    const lines: string[] = [];
    
    lines.push('REM Set environment variables');
    lines.push(`SET WATCOM=${watcomPath}`);
    lines.push(`SET PATH=%WATCOM%\\BINW;%PATH%`);
    lines.push(`SET INCLUDE=%WATCOM%\\H`);
    lines.push(`SET LIB=%WATCOM%\\LIB286\\DOS`);
    
    // Add custom environment variables if provided
    if (options?.envVars) {
      for (const [key, value] of Object.entries(options.envVars)) {
        lines.push(`SET ${key}=${value}`);
      }
    }
    
    return lines;
  }

  /**
   * Generate environment setup commands as a single string
   * 
   * Convenience method for getting environment setup as a string.
   * 
   * @param watcomPath - Path to WATCOM installation
   * @returns Environment setup commands
   */
  static generateEnvSetup(watcomPath: string): string {
    return this.generateEnvSetupLines(watcomPath).join('\r\n');
  }
}

